import { LanguageToggle } from "@/components/LanguageToggle";
import { copy, type Locale } from "@/lib/locale";
import { trpc } from "@/lib/trpc";
import { apiUrl } from "@/lib/apiOrigin";
import { CheckCircle2, Circle, ExternalLink, Loader2, Send, ShieldCheck, WalletCards } from "lucide-react";
import { useState } from "react";
import { useRoute } from "wouter";

export default function Handoff() {
  const [, params] = useRoute("/handoff/:token");
  const token = params?.token ?? "";
  const [locale, setLocale] = useState<Locale>("es");
  const handoff = trpc.openStay.public.handoff.useQuery({ token, locale }, { enabled: Boolean(token), retry: false });
  const complete = trpc.openStay.public.completeHandoff.useMutation({ onSuccess: () => handoff.refetch() });
  const appleWallet = trpc.openStay.public.walletStatus.useQuery({ platform: "apple", locale });
  const googleWallet = trpc.openStay.public.walletStatus.useQuery({ platform: "google", locale });
  const googleSave = trpc.openStay.public.googleWalletSave.useMutation({ onSuccess: ({ saveUrl }) => window.location.assign(saveUrl) });
  if (handoff.isLoading) return <div className="status-screen folios-surface folios-status-screen"><div className="folios-status-mark">F</div><p className="eyebrow">FOLIOS · EXPEDIENTE SEGURO</p><Loader2 className="spin folios-status-icon" /><h1>{copy(locale, "Abriendo el expediente", "Opening the record")}</h1><p>{copy(locale, "Validando el enlace firmado y su estado actual.", "Validating the signed link and its current status.")}</p><small>{copy(locale, "VALIDACIÓN EN CURSO", "VALIDATION IN PROGRESS")}</small></div>;
  if (handoff.error || !handoff.data) return <div className="status-screen folios-surface folios-status-screen"><div className="folios-status-mark">F</div><p className="eyebrow">FOLIOS · EXPEDIENTE NO DISPONIBLE</p><ShieldCheck className="folios-status-icon" size={28} /><h1>{copy(locale, "Este enlace ya no está disponible", "This link is no longer available")}</h1><p>{copy(locale, "Pide un enlace nuevo al operador. El registro original se conserva, pero este acceso ya no es válido.", "Ask the operator for a new link. The original record is preserved, but this access is no longer valid.")}</p><small>{copy(locale, "SIGUIENTE ACCIÓN · SOLICITAR ENLACE", "NEXT ACTION · REQUEST LINK")}</small></div>;
  const { handoff: item, invoiceHistory } = handoff.data;
  const steps = [
    [copy(locale, "Capturar", "Capture"), item.sourceContent],
    [copy(locale, "Contexto", "Context"), item.context],
    [copy(locale, "Revisar", "Check"), item.checkState === "ready" ? copy(locale, "Listo para compartir", "Ready to share") : copy(locale, "Necesita revisión", "Needs review")],
    [copy(locale, "Responsable", "Owner"), item.ownerName],
    [copy(locale, "Enviar", "Hand off"), item.status === "completed" ? copy(locale, "Handoff completado", "Handoff complete") : copy(locale, "Confirmar y enviar el enlace", "Confirm and send the link")],
  ];
  const stateLabel = item.status === "completed" ? copy(locale, "● COMPLETADO", "● COMPLETED") : item.checkState === "ready" ? copy(locale, "● LISTO", "● READY") : copy(locale, "○ REVISAR", "○ REVIEW");
  const invoiceMeta = { proof: { label: copy(locale, "COMPROBANTE", "PROOF SLIP"), color: "#d9a441" }, review: { label: copy(locale, "FACTURA EN REVISIÓN", "INVOICE IN REVIEW"), color: "#aa8bd8" }, issued: { label: copy(locale, "FACTURA EMITIDA", "INVOICE ISSUED"), color: "#39d98a" }, cancelled: { label: copy(locale, "FACTURA CANCELADA", "INVOICE CANCELLED"), color: "#e17878" } } as const;
  const invoice = invoiceMeta[item.invoiceStatus ?? "proof"];
  const canAddToWallet = item.invoiceStatus === "issued" && Boolean(item.invoiceNumber);
  const applePassUrl = apiUrl(`/wallet/apple?token=${encodeURIComponent(token)}&locale=${locale}`);
  return <main className="handoff-page folios-surface"><header className="guest-header"><div className="folios-lockup">FOLIOS<span>.WORKS</span><small>{copy(locale, "UN REGISTRO", "ONE RECORD")}</small></div><LanguageToggle locale={locale} onChange={setLocale} /></header><section className="folio-hero"><p className="eyebrow emerald">{copy(locale, "HANDOFF DE PRUEBA", "PROOF HANDOFF")}</p><h1>{item.title}</h1><p>{copy(locale, "Una cosa clara. Un siguiente movimiento.", "One clear thing. One next move.")}</p><div className={`folio-status ${item.status}`}>{stateLabel}</div><div className="invoice-state-badge" style={{ borderColor: invoice.color, color: invoice.color }}><span>{invoice.label}</span>{item.invoiceNumber ? <strong>{item.invoiceNumber}</strong> : null}{item.invoiceUrl ? <a href={item.invoiceUrl} target="_blank" rel="noreferrer">{copy(locale, "Ver factura", "View invoice")}</a> : null}</div></section>
  <section className="handoff-steps">{steps.map(([label, body], index) => <article key={label} className={`handoff-step ${index === 4 ? "handoff-final" : ""}`}><div className="step-index">{index === 4 && item.status !== "completed" ? <Circle size={18} /> : <CheckCircle2 size={18} />}{String(index + 1).padStart(2, "0")}</div><div><p className="eyebrow">{label}</p><p>{body}</p></div>{index === 0 && item.sourceType === "link" ? <ExternalLink size={16} /> : null}</article>)}</section>{canAddToWallet ? <section className="wallet-actions" aria-label={copy(locale, "Agregar factura a Wallet", "Add invoice to Wallet")}><p className="eyebrow">{copy(locale, "CREDENCIAL FISCAL", "FISCAL CREDENTIAL")}</p><h2>{copy(locale, "Guarda esta factura emitida", "Save this issued invoice")}</h2><p>{copy(locale, "El QR mantiene el mismo enlace seguro de Folios; Wallet muestra el estado fiscal vigente.", "The QR keeps the same secure Folios link; Wallet shows the current fiscal state.")}</p><div>{appleWallet.data?.state === "ready" ? <a className="wallet-button apple" href={applePassUrl}><WalletCards size={17} /> {copy(locale, "Agregar a Apple Wallet", "Add to Apple Wallet")}</a> : null}{googleWallet.data?.state === "ready" ? <button className="wallet-button google" type="button" onClick={() => googleSave.mutate({ token, locale, baseUrl: window.location.origin })} disabled={googleSave.isPending}><WalletCards size={17} /> {googleSave.isPending ? copy(locale, "Abriendo Wallet…", "Opening Wallet…") : copy(locale, "Agregar a Google Wallet", "Add to Google Wallet")}</button> : null}</div>{googleSave.error ? <small>{copy(locale, "No se pudo abrir Google Wallet. Verifica la configuración del emisor.", "Google Wallet could not be opened. Verify issuer configuration.")}</small> : null}</section> : null}{invoiceHistory?.length ? <section className="invoice-history" aria-label={copy(locale, "Historial de factura", "Invoice history")}><p className="eyebrow">{copy(locale, "HISTORIAL DE FACTURA", "INVOICE HISTORY")}</p>{invoiceHistory.map((event, index) => <div key={`${event.createdAt}-${index}`}><span>{event.type === "invoice_issued" ? copy(locale, "Factura emitida", "Invoice issued") : copy(locale, "Estado actualizado", "Status updated")}</span><time dateTime={new Date(event.createdAt).toISOString()}>{new Date(event.createdAt).toLocaleString(locale === "es" ? "es-MX" : "en-US")}</time></div>)}</section> : null}{item.status !== "completed" ? <button className="complete-handoff" type="button" onClick={() => complete.mutate({ token, locale })} disabled={complete.isPending}><Send size={17} /> {copy(locale, "Completar handoff", "Complete handoff")}</button> : <div className="completed-note"><CheckCircle2 size={18} /> {copy(locale, "El operador fue notificado.", "The operator was notified.")}</div>}<footer className="guest-footer">{copy(locale, "Prueba y siguiente paso", "Proof and next step")} · FOLIOS.WORKS</footer></main>;
}
