import FirstPropertyGuide from "@/components/FirstPropertyGuide";
import QrCredentialPreview from "@/components/QrCredentialPreview";
import DashboardLayout from "@/components/DashboardLayout";
import { LanguageToggle } from "@/components/LanguageToggle";
import { copy, formatDate, type Locale } from "@/lib/locale";
import { trpc } from "@/lib/trpc";
import { Bell, Check, Clipboard, KeyRound, Link2, Loader2, Nfc, Plus, ShieldBan, WalletCards } from "lucide-react";
import { lazy, Suspense, useMemo, useState } from "react";
import "./operator-extra.css";
import "./operator-enhancements.css";

const TicketStatusPreview = lazy(() => import("@/components/TicketStatusPreview").then(module => ({ default: module.TicketStatusPreview })));
const InvoiceLifecyclePanel = lazy(() => import("@/components/InvoiceLifecyclePanel").then(module => ({ default: module.InvoiceLifecyclePanel })));
const QrCodeToText = lazy(() => import("@/components/QrCodeToText").then(module => ({ default: module.QrCodeToText })));

export default function Operator() {
  const [locale, setLocale] = useState<Locale>("es");
  const [stayResult, setStayResult] = useState<{ arrivalUrl: string; nfcUri: string; qrDataUrl: string } | null>(null);
  const [handoffResult, setHandoffResult] = useState<{ handoffUrl: string; qrDataUrl: string } | null>(null);
  const [sharedCredential, setSharedCredential] = useState<{ link: string; nfcUri: string | null; qrDataUrl: string } | null>(null);
  const [copied, setCopied] = useState("");
  const records = trpc.openStay.operator.dashboard.useQuery();
  const createStay = trpc.openStay.operator.createStay.useMutation({ onSuccess: data => { setStayResult(data); records.refetch(); } });
  const createHandoff = trpc.openStay.operator.createHandoff.useMutation({ onSuccess: data => { setHandoffResult(data); records.refetch(); } });
  const revoke = trpc.openStay.operator.revokeCredential.useMutation({ onSuccess: () => records.refetch() });
  const shareCredential = trpc.openStay.operator.shareCredential.useMutation({ onSuccess: setSharedCredential });
  const updateNotificationSettings = trpc.openStay.operator.updateNotificationSettings.useMutation({ onSuccess: () => records.refetch() });
  const updateInvoiceStatus = trpc.openStay.operator.updateInvoiceStatus.useMutation({ onSuccess: () => records.refetch() });
  const apple = trpc.openStay.public.walletStatus.useQuery({ platform: "apple", locale });
  const google = trpc.openStay.public.walletStatus.useQuery({ platform: "google", locale });
  const baseUrl = useMemo(() => typeof window === "undefined" ? "https://open-stay-pass.example" : window.location.origin, []);
  const copyLink = async (value: string, label: string) => { await navigator.clipboard.writeText(value); setCopied(label); window.setTimeout(() => setCopied(""), 1600); };

  return <DashboardLayout><main className="operator-console"><header className="operator-header"><div><p className="eyebrow emerald">OPEN STAY PASS / OPERATOR</p><h1>{copy(locale, "Operación clara. Credenciales bajo control.", "Clear operations. Credentials in control.")}</h1></div><LanguageToggle locale={locale} onChange={setLocale} /></header>
    <section className="operator-stats"><div><span>{records.data?.stays.length ?? 0}</span><p>{copy(locale, "estancias", "stays")}</p></div><div><span>{records.data?.credentials.filter(item => item.status === "active").length ?? 0}</span><p>{copy(locale, "credenciales activas", "active credentials")}</p></div><div><span>{records.data?.handoffs.length ?? 0}</span><p>{copy(locale, "handoffs", "handoffs")}</p></div></section>
    <section className="operator-grid"><FirstPropertyGuide locale={locale} baseUrl={baseUrl} isCreating={createStay.isPending} onCreate={input => createStay.mutate(input)} />
      <form className="operator-form folios-form" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); createHandoff.mutate({ title: String(form.get("title")), sourceType: "note", sourceContent: String(form.get("source")), context: String(form.get("context")), checkState: String(form.get("check")) as "ready" | "needs_review", ownerName: String(form.get("owner")), locale, baseUrl }); }}><div className="form-heading"><div><p className="eyebrow emerald">FOLIOS</p><h2>{copy(locale, "Crear handoff", "Create handoff")}</h2></div><KeyRound /></div><label>{copy(locale, "Título", "Title")}<input required name="title" placeholder={copy(locale, "Una cosa para entregar", "One thing to hand off")} /></label><label>{copy(locale, "Capturar", "Capture")}<textarea required name="source" placeholder={copy(locale, "Pega una nota, enlace o descripción de foto.", "Paste a note, link, or photo description.")} /></label><label>{copy(locale, "Contexto", "Context")}<textarea required name="context" placeholder={copy(locale, "¿Por qué importa? Una frase.", "Why does it matter? One sentence.")} /></label><div className="form-split"><label>{copy(locale, "Revisión", "Check")}<select name="check"><option value="ready">{copy(locale, "Listo", "Ready")}</option><option value="needs_review">{copy(locale, "Necesita revisión", "Needs review")}</option></select></label><label>{copy(locale, "Responsable", "Owner")}<input required name="owner" placeholder="María" /></label></div><button className="form-submit folios-submit" disabled={createHandoff.isPending}><Plus size={16} /> {createHandoff.isPending ? "…" : copy(locale, "Generar handoff", "Generate handoff")}</button>{handoffResult ? <div className="result-block"><img src={handoffResult.qrDataUrl} alt="Handoff QR code" /><div><p>{copy(locale, "Link seguro listo", "Secure link ready")}</p><button type="button" onClick={() => copyLink(handoffResult.handoffUrl, "handoff")}><Clipboard size={14} /> {copied === "handoff" ? <Check size={14} /> : null}{copy(locale, "Copiar handoff", "Copy handoff")}</button></div></div> : null}</form></section>
    <QrCredentialPreview locale={locale} isLoading={createStay.isPending} qrDataUrl={stayResult?.qrDataUrl} link={stayResult?.arrivalUrl} nfcUri={stayResult?.nfcUri} copied={copied} label="arrival" onCopy={copyLink} />
    <Suspense fallback={null}><TicketStatusPreview /></Suspense>
    <Suspense fallback={null}><InvoiceLifecyclePanel locale={locale} handoffs={records.data?.handoffs ?? []} onStatusChange={(handoffId, invoiceStatus) => updateInvoiceStatus.mutate({ handoffId, invoiceStatus, locale })} /></Suspense>
    <Suspense fallback={null}><QrCodeToText locale={locale} onVerify={value => { window.open(value, "_blank", "noopener,noreferrer"); }} /></Suspense>
        <section className="operator-section"><div className="section-title"><div><p className="eyebrow">{copy(locale, "Credenciales", "Credentials")}</p><h2>{copy(locale, "Estancias y estado", "Stays and status")}</h2></div><ShieldBan size={19} /></div>
{records.isLoading ? <div className="loading-row"><Loader2 className="spin" /> {copy(locale, "Cargando", "Loading")}</div> : <div className="credential-list">{records.data?.credentials.length ? records.data.credentials.map(item => <article key={item.id}><div><span className={`status-dot ${item.status}`} /> <strong>{item.type === "arrival" ? "HOSTCASA" : "FOLIOS"}</strong><small>{formatDate(item.expiresAt, locale)}</small></div><span className="credential-state">{item.status === "active" ? copy(locale, "activo", "active") : item.status === "revoked" ? copy(locale, "revocado", "revoked") : copy(locale, "expirado", "expired")}</span>{item.status === "active" ? <div className="credential-actions"><button type="button" onClick={() => shareCredential.mutate({ credentialId: item.id, baseUrl })}><Link2 size={13} /> {copy(locale, "Copiar", "Copy")}</button><button type="button" onClick={() => revoke.mutate({ credentialId: item.id })}>{copy(locale, "Revocar", "Revoke")}</button></div> : null}</article>) : <p className="empty-state">{copy(locale, "Todavía no hay credenciales. Crea tu primera llegada o handoff.", "No credentials yet. Create your first arrival or handoff.")}</p>}</div>}{sharedCredential ? <QrCredentialPreview locale={locale} qrDataUrl={sharedCredential.qrDataUrl} link={sharedCredential.link} nfcUri={sharedCredential.nfcUri} copied={copied} label="stored" onCopy={copyLink} /> : null}</section>
    <section className="operator-section notification-section"><div className="section-title"><div><p className="eyebrow">{copy(locale, "Alertas", "Alerts")}</p><h2>{copy(locale, "Notificaciones del operador", "Operator notifications")}</h2></div><Bell size={19} /></div><div className="notification-control"><label>{copy(locale, "Entrega", "Delivery")}<select value={records.data?.notificationSettings.channel ?? "in_app_only"} onChange={event => updateNotificationSettings.mutate({ channel: event.target.value as "project_owner_push" | "in_app_only", enabled: records.data?.notificationSettings.enabled ?? true })}><option value="in_app_only">{copy(locale, "Solo en esta consola", "In this console only")}</option><option value="project_owner_push">{copy(locale, "Push al propietario del proyecto", "Push to project owner")}</option></select></label><p>{copy(locale, "Las alertas siempre quedan registradas aquí. El push usa la cuenta propietaria del proyecto cuando está disponible.", "Alerts are always recorded here. Push uses the project owner account when available.")}</p></div><div className="notification-list">{records.data?.notifications.length ? records.data.notifications.map(notification => <article key={notification.id}><span className={`status-dot ${notification.deliveryStatus === "unavailable" ? "revoked" : "active"}`} /><div><strong>{locale === "es" ? notification.titleEs : notification.titleEn}</strong><p>{locale === "es" ? notification.detailEs : notification.detailEn}</p></div><small>{formatDate(notification.createdAt, locale)}</small></article>) : <p className="empty-state">{copy(locale, "Aún no hay actividad. Aquí aparecerán scans y handoffs completados.", "No activity yet. Scans and completed handoffs will appear here.")}</p>}</div></section>
    <section className="wallet-row"><div><WalletCards size={19} /><div><p className="eyebrow">APPLE WALLET</p><strong>{apple.data?.state === "ready" ? copy(locale, "Listo", "Ready") : copy(locale, "Configuración requerida", "Configuration required")}</strong></div></div><div><WalletCards size={19} /><div><p className="eyebrow">GOOGLE WALLET</p><strong>{google.data?.state === "ready" ? copy(locale, "Listo", "Ready") : copy(locale, "Configuración requerida", "Configuration required")}</strong></div></div></section>
  </main></DashboardLayout>;
}
